name: Release App
on:
  push:
    tags: "*.*.*"

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Get current time
        uses: MyJetTools/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
          utcOffset: "+00:00"

      - name: ls
        run: ls -la
        
      - name: pwd
        run: pwd

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish Service
        run: dotnet publish --configuration Release --output ./publish-api
      - name: Check Service dir
        run: ls ./publish-api

      - name: Publish image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./publish-api
          repository: myjettools/trade-log-ui
          tags: ${{ steps.vars.outputs.tag }}
          build_args: ui_version=${{ steps.vars.outputs.tag }},app_version=${{ steps.string.outputs.lowercase }}:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}
